package com.spean90.webservice.service.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import com.spean90.webservice.service.IMyService2;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2015-01-26T13:05:44.908+08:00
 * Generated source version: 3.0.3
 * 
 */
@WebServiceClient(name = "MyService2ImplService", 
                  wsdlLocation = "http://localhost/myws2?wsdl",
                  targetNamespace = "http://impl.service.webservice.spean90.com/") 
public class MyService2ImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.service.webservice.spean90.com/", "MyService2ImplService");
    public final static QName MyService2ImplPort = new QName("http://impl.service.webservice.spean90.com/", "MyService2ImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost/myws2?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MyService2ImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost/myws2?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MyService2ImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MyService2ImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyService2ImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MyService2ImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MyService2ImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MyService2ImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns IMyService2
     */
    @WebEndpoint(name = "MyService2ImplPort")
    public IMyService2 getMyService2ImplPort() {
        return super.getPort(MyService2ImplPort, IMyService2.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IMyService2
     */
    @WebEndpoint(name = "MyService2ImplPort")
    public IMyService2 getMyService2ImplPort(WebServiceFeature... features) {
        return super.getPort(MyService2ImplPort, IMyService2.class, features);
    }

}
