package com.spean90.webservice.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2015-01-26T17:27:10.023+08:00
 * Generated source version: 3.0.3
 * 
 */
@WebService(targetNamespace = "http://service.webservice.spean90.com/", name = "IMyService2")
@XmlSeeAlso({ObjectFactory.class})
public interface IMyService2 {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "division", targetNamespace = "http://service.webservice.spean90.com/", className = "com.spean90.webservice.service.Division")
    @WebMethod
    @ResponseWrapper(localName = "divisionResponse", targetNamespace = "http://service.webservice.spean90.com/", className = "com.spean90.webservice.service.DivisionResponse")
    public int division(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "multiply", targetNamespace = "http://service.webservice.spean90.com/", className = "com.spean90.webservice.service.Multiply")
    @WebMethod
    @ResponseWrapper(localName = "multiplyResponse", targetNamespace = "http://service.webservice.spean90.com/", className = "com.spean90.webservice.service.MultiplyResponse")
    public int multiply(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );
}
